services:
  
  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi-bridge
    ports:
      - "8080:8080"
      - "9999:9999"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=supersecretpassword123
    volumes:
      - nifi-data:/opt/nifi/nifi-current/conf
    networks:
      - iot_network

  # --- AJOUT DE RABBITMQ (Remplacement de Kafka) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"   # Port principal pour la communication AMQP
      - "15672:15672" # Port pour l'interface web de management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersecretpassword123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - iot_network

  
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=IoTCluster
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - iot_network

  
  python-consumer:
    build:
      context: .
      dockerfile: processors/Dockerfile
    container_name: python-consumer
    depends_on:
      - rabbitmq # Mis à jour : attend RabbitMQ
      - cassandra
    networks:
      - iot_network
    restart: always

  live-dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: streamlit-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - rabbitmq # Mis à jour : attend RabbitMQ
    networks:
      - iot_network
    restart: always

networks:
  iot_network:
    driver: bridge

volumes:
  nifi-data:
  cassandra-data:
  rabbitmq-data: # Nouveau volume pour RabbitMQ (remplace kafka-data)